version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  # checkoutAndTest:
  #   machine: true
  #   steps:
  #   - checkout
  #   - run: npm run test
  integrateFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run: git clone https://github.com/elimowa/3w5-h22-tp2-frontend.git; git clone https://github.com/elimowa/3w5-h22-tp2-backend.git;
      - run: cd 3w5-h22-tp2-frontend/ && npm i
      - run: cd 3w5-h22-tp2-frontend/ && npm run build
      - run: cd 3w5-h22-tp2-backend/ && mkdir public
      - run: cp -rT 3w5-h22-tp2-frontend/build  3w5-h22-tp2-backend/public 
      - persist_to_workspace:
          root: .
          paths:
            - 3w5-h22-tp2-backend
  deploy:
    machine: true
    steps:
    - attach_workspace:
        at: .
    - run: cd 3w5-h22-tp2-backend/ && ls -Rl
    
workflows:

  build:
    jobs:
      - node/test
      - integrateFrontend:
          requires:
            - node/test
      - deploy:
          requires:
            - integrateFrontend
  

